# Generated by Django 5.1.1 on 2024-12-15 09:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_student_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='custom_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
