# Generated by Django 5.1.1 on 2024-12-15 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_student_custom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='custom_id',
        ),
    ]
