# Generated by Django 5.1.1 on 2024-12-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_student_custom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='custom_id',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
    ]
