# Generated by Django 5.1.1 on 2024-12-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_student_custom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarian',
            name='custom_id',
        ),
        migrations.RemoveField(
            model_name='libraryhistory',
            name='custom_id',
        ),
        migrations.RemoveField(
            model_name='office_staff',
            name='custom_id',
        ),
        migrations.RemoveField(
            model_name='office_staff',
            name='student_details',
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
